(() => {
  "use strict";
  const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const stage={INFORMATION_ONLY:"有信息但没有充值",RECHARGED_NO_CONSUMPTION:"已充值但没有消费",RECHARGED_WITH_CONSUMPTION:"已充值并已有消费"};
  let mode="select", rows=[], pending=null, loading=false;
  const resultData=r=>{for(const x of [r?.result,r?.data?.result,r?.data,r]){if(x&&typeof x==="object"&&("ok" in x||"message" in x))return x;try{const p=JSON.parse(x);if(p&&typeof p==="object")return p}catch(_){}}return {}};
  function register(fn){try{fn?.(window.cloudbase)}catch(e){if(!String(e?.message||"").includes("duplicate component"))throw e}}
  async function call(data){
    if(!window.cloudbase||!window.CloudBaseAuthConfig||!window.registerFunctions)throw Error("数据库组件未加载，请刷新页面后重试。");
    register(window.registerAuth);register(window.registerFunctions);
    let r;try{r=await window.cloudbase.init(window.CloudBaseAuthConfig).callFunction({name:"faceRecognition",data})}catch(e){throw Error(e?.message||"数据库查询失败，请检查网络和登录状态。")}
    const d=resultData(r);if(!d.ok)throw Error(d.message||"数据库没有返回有效结果。");return d;
  }
  function payload(){const process={all:"ALL",registered:"INFORMATION_ONLY",charged:"RECHARGED_NO_CONSUMPTION",consumed:"RECHARGED_WITH_CONSUMPTION"};return mode==="manual"?{action:"queryStoreCustomers",mode:"manual",name:$("customerName").value.trim(),birthDate:$("customerBirthday").value}:{action:"queryStoreCustomers",mode:"browse",processStatus:process[$("customerCategory").value]||"ALL",customerStatus:$("customerArchive").value,startDate:$("customerDateStart").value,endDate:$("customerDateEnd").value}}
  function render(){
    const active=rows.filter(x=>x.customerStatus==="ACTIVE").length;
    $("customerSummary").textContent=`共 ${rows.length} 位客户；活跃 ${active} 位，封存 ${rows.length-active} 位`;
    $("customerQueryBody").innerHTML=rows.map(c=>{const archived=c.customerStatus==="ARCHIVED",bd=String(c.birthDate||"").replace(/^(\d{4})-(\d{2})-(\d{2}).*/,"$1年$2月$3日"),link=`customer-detail.html?customerId=${encodeURIComponent(c.customerCode)}&customerName=${encodeURIComponent(c.customerName)}`;return `<tr><td><a class="record-link" href="${link}">${esc(c.customerCode)}</a></td><td>${esc(c.customerName)}</td><td>${bd||"—"}</td><td>${esc([c.storeName,c.storeCode].filter(Boolean).join(" · ")||"—")}</td><td>${esc(stage[c.customerProcessStatus]||"—")}</td><td>${Number(c.totalRechargeCount||0)}</td><td>${Number(c.totalVerificationCount||0)}</td><td><span class="record-status ${archived?"status-已作废":"status-正常"}">${archived?"封存":"活跃"}</span></td><td><button class="archive-customer-button" data-code="${esc(c.customerCode)}" data-status="${c.customerStatus}">${archived?"恢复为活跃":"封存客户"}</button></td></tr>`}).join("")||'<tr><td colspan="9" class="query-empty">没有符合条件的客户</td></tr>';
    document.querySelectorAll("[data-code]").forEach(b=>b.onclick=()=>openStatus(b.dataset.code,b.dataset.status));renderCategories();
  }
  function renderCategories(){const n={all:rows.length,registered:0,charged:0,consumed:0};rows.forEach(x=>{if(x.customerProcessStatus==="INFORMATION_ONLY")n.registered++;else if(x.customerProcessStatus==="RECHARGED_NO_CONSUMPTION")n.charged++;else if(x.customerProcessStatus==="RECHARGED_WITH_CONSUMPTION")n.consumed++});const labels={all:"全部客户",registered:"有信息但没有充值",charged:"已充值但没有消费",consumed:"已充值并已有消费"};$("customerCategoryGrid").innerHTML=Object.entries(labels).map(([k,v])=>`<button class="customer-category-card ${$("customerCategory").value===k?"selected":""}" data-category="${k}"><span>${v}</span><strong>${n[k]}</strong><small>当前查询结果</small></button>`).join("");document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>{$("customerCategory").value=b.dataset.category;mode="select";load()})}
  async function load(){if(loading)return;loading=true;$("customerQueryBody").innerHTML='<tr><td colspan="9" class="query-empty">正在从数据库读取本门店客户…</td></tr>';try{const d=await call(payload());rows=Array.isArray(d.customers)?d.customers:[];$("customerStoreName").textContent=[d.storeName||"当前门店",d.storeCode||""].filter(Boolean).join(" · ");render()}catch(e){rows=[];$("customerSummary").textContent="数据库读取失败";$("customerQueryBody").innerHTML=`<tr><td colspan="9" class="query-empty">${esc(e.message)}</td></tr>`;$("customerCategoryGrid").innerHTML=""}finally{loading=false}}
  function setMode(next){if(next!==mode){if(next==="select"){$("customerName").value="";$("customerBirthday").value="";$("customerBirthday").syncChineseBirthday?.()}else{$("customerCategory").value="all";$("customerArchive").value="all"}}mode=next;document.querySelectorAll("[data-customer-query-mode]").forEach(x=>x.classList.toggle("active",x.dataset.customerQueryMode===mode));document.querySelectorAll("[data-customer-query-panel]").forEach(x=>x.classList.toggle("active",x.dataset.customerQueryPanel===mode))}
  function openStatus(code,status){pending={code,status};const archived=status==="ARCHIVED";$("customerActionTitle").textContent=archived?"恢复为活跃":"设为存档";$("customerActionText").textContent=archived?`将客户 ${code} 恢复为活跃。`:`将客户 ${code} 设为存档。`;$("customerActionDialog").showModal()}
  async function confirm(){if(!pending)return;try{await call({action:"updateCustomerStatus",customerCode:pending.code,expectedStatus:pending.status,targetStatus:pending.status==="ARCHIVED"?"ACTIVE":"ARCHIVED"});$("customerActionDialog").close();load()}catch(e){$("customerActionText").textContent=e.message}}
  function range(){const t=new Date(),s=new Date(t),r=$("customerTimeRange").value;if(r==="sevenDays")s.setDate(t.getDate()-6);else if(r==="month")s.setMonth(t.getMonth()-1);else if(r==="quarter")s.setMonth(Math.floor(t.getMonth()/3)*3,1);else if(r==="year")s.setMonth(0,1);else s.setFullYear(t.getFullYear()-1);if(r!=="custom"||!$("customerDateStart").value){$("customerDateStart").value=s.toISOString().slice(0,10);$("customerDateEnd").value=t.toISOString().slice(0,10)}$("customerDateStart").disabled=r!=="custom";$("customerDateEnd").disabled=r!=="custom"}
  range();document.querySelectorAll("[data-customer-query-mode],[data-customer-query-panel]").forEach(x=>x.onclick=()=>{setMode(x.dataset.customerQueryMode||x.dataset.customerQueryPanel);load()});["customerCategory","customerArchive","customerDateStart","customerDateEnd"].forEach(id=>$(id).onchange=()=>{mode="select";load()});$("customerTimeRange").onchange=()=>{range();mode="select";load()};["customerName","customerBirthday"].forEach(id=>$(id).onchange=()=>{mode="manual";load()});$("resetCustomerQuery").onclick=()=>{$("customerCategory").value="all";$("customerArchive").value="all";$("customerName").value="";$("customerBirthday").value="";$("customerTimeRange").value="custom";range();mode="select";load()};$("closeCustomerAction").onclick=$("cancelCustomerAction").onclick=()=>$("customerActionDialog").close();$("confirmCustomerAction").onclick=confirm;load();
})();
