(() => {
  "use strict";
  const VERSION = "0.14.21", p = new URLSearchParams(location.search), $ = (id) => document.getElementById(id), id = p.get("teacherId") || "T001", seed = Number(id.replace(/\D/g, "")) || 1;
  const name = `业务老师 ${String(seed).padStart(2, "0")}`, cities = ["悉尼", "墨尔本", "布里斯班", "珀斯"], projects = ["普拉提", "体态评估", "康复训练", "瑜伽", "力量训练", "产后恢复"];
  const info = (items) => items.map(([k, v]) => `<article><span>${k}</span><strong>${v}</strong></article>`).join("");
  $("teacherHero").innerHTML = `<div class="profile-avatar teacher-profile-avatar">${String(seed).padStart(2, "0")}</div><div><span class="profile-type">老师编号</span><h2>${name}</h2><p>${id} · 在职 · 可执行核销</p></div><div class="profile-metrics"><span><strong>${2 + seed % 4}</strong>关联门店</span><span><strong>${4 + seed % 3}</strong>授权项目</span><span><strong>${186 + seed * 7}</strong>本年核销</span></div>`;
  $("teacherBasicGrid").innerHTML = info([["老师编号", id], ["老师姓名", name], ["显示名称", `老师${seed}`], ["任职状态", "在职"], ["入职日期", `2023-${String(seed % 12 + 1).padStart(2, "0")}-15`], ["主要门店", `${cities[seed % 4]}门店 ${seed % 16 + 1}`], ["联系电话", "按权限脱敏显示"], ["最后修改", "HQ001 · 总部管理员"]]);
  const assignments = Array.from({ length: 12 }, (_, i) => { const storeNo = (seed + Math.floor(i / 4)) % 16 + 1, projectNo = i % 4 + 1; return { storeId: `S${String(storeNo).padStart(3, "0")}`, store: `${cities[(seed + Math.floor(i / 4)) % 4]}门店 ${storeNo}`, projectId: `P${String(projectNo).padStart(3, "0")}`, project: projects[projectNo - 1] }; });
  $("teacherAssignmentBody").innerHTML = assignments.map((a, i) => `<tr><td><a class="record-link" href="store-detail.html?storeId=${a.storeId}">${a.storeId}</a></td><td>${a.store}</td><td><a class="record-link" href="project-detail.html?projectId=${a.projectId}">${a.project}</a></td><td>202${3 + i % 3}-0${i % 9 + 1}-01</td><td>有效</td></tr>`).join("");
  $("teacherStatsBody").innerHTML = assignments.map((a, i) => { const count = 18 + (seed * 5 + i * 9) % 70; return `<tr><td><a class="record-link" href="store-detail.html?storeId=${a.storeId}">${a.store}</a></td><td><a class="record-link" href="project-detail.html?projectId=${a.projectId}">${a.project}</a></td><td>${count}</td><td>${i % 5 === 0 ? 1 : 0}</td><td>${i % 7 === 0 ? 1 : 0}</td><td>${(5.5 + i * 1.7).toFixed(1)}%</td></tr>`; }).join("");
  $("teacherRecordBody").innerHTML = Array.from({ length: 12 }, (_, i) => { const customerId = `C${String(seed).padStart(3, "0")}${String(i + 1).padStart(3, "0")}`, recordId = `VE-${id}-${String(i + 1).padStart(3, "0")}`, a = assignments[i]; return `<tr><td><a class="record-link" href="verification-detail.html?recordId=${recordId}&customerId=${customerId}&customerName=${encodeURIComponent(`客户${i + 1}`)}&storeId=${a.storeId}">${recordId}</a></td><td>2026-08-${String(12 - i % 10).padStart(2, "0")}</td><td><a class="record-link" href="store-detail.html?storeId=${a.storeId}">${a.store}</a></td><td><a class="record-link" href="project-detail.html?projectId=${a.projectId}">${a.project}</a></td><td><a class="record-link" href="customer-detail.html?customerId=${customerId}&customerName=${encodeURIComponent(`客户${i + 1}`)}&storeId=${a.storeId}">${customerId}</a></td><td><span class="photo-required-status">已拍摄</span></td><td>发送成功</td><td>${i === 8 ? "作废待审核" : "正常"}</td></tr>`; }).join("");
  $("teacherAuditTimeline").innerHTML = `<div><strong>2023-04-15</strong><span>HQ001 · 总部管理员创建老师档案</span></div><div><strong>2025-09-03</strong><span>OP001 · 运营管理员增加项目授权</span></div><div><strong>2026-07-18</strong><span>HQ001 · 总部管理员更新主要门店</span></div>`;
  document.documentElement.dataset.prototypeVersion = VERSION;
})();
