"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const rootHtml = fs.readdirSync(root).filter((file) => file.endsWith(".html")).sort();
const rootJs = fs.readdirSync(root).filter((file) => file.endsWith(".js")).sort();

function localTarget(raw) {
  const value = String(raw || "").trim();
  if (!value || /^(?:https?:|data:|blob:|mailto:|tel:|javascript:|#)/i.test(value)) return "";
  const target = value.split(/[?#]/)[0].replace(/^\.\//, "");
  if (!target || target.includes("${") || target.startsWith("/")) return "";
  return decodeURIComponent(target);
}

test("every root Web page resolves all static local links and assets", () => {
  assert.ok(rootHtml.length >= 45, "the complete Web route set must be checked");
  for (const page of rootHtml) {
    const html = read(page);
    assert.match(html, /<meta name="viewport"/, `${page} needs a responsive viewport`);
    for (const match of html.matchAll(/\b(?:href|src)=["']([^"']+)["']/gi)) {
      const target = localTarget(match[1]);
      if (!target) continue;
      assert.ok(fs.existsSync(path.join(root, target)), `${page} references missing local target ${target}`);
    }
    if (!["login.html", "rating.html", "teacher-detail.html"].includes(page)) {
      assert.match(html, /auth-ui\.js\?v=0\.21\.0/, `${page} must use the current permission/navigation shell`);
    }
  }
});

test("every literal Web route generated by JavaScript exists", () => {
  for (const sourceFile of rootJs) {
    const source = read(sourceFile);
    for (const match of source.matchAll(/["'`](?:\.\/)?([a-z0-9][a-z0-9-]*\.html)(?:[?#][^"'`]*)?["'`]/gi)) {
      assert.ok(fs.existsSync(path.join(root, match[1])), `${sourceFile} generates missing route ${match[1]}`);
    }
  }
});

test("critical detail links cover teacher, store, customer, project and work-order navigation", () => {
  const expectations = {
    "teacher-management.js": [/staff-detail\.html\?role=teacher/],
    "store-management.js": [/store-detail\.html\?storeId=/],
    "customer-query.js": [/customer-detail\.html\?customerId=/],
    "management.js": [/project-detail\.html\?projectId=/, /store-detail\.html\?storeId=/, /staff-detail\.html\?role=/, /customer-detail\.html\?customerId=/],
    "query.js": [/recharge-detail\.html/, /verification-detail\.html/, /customer-detail\.html\?customerId=/, /staff-detail\.html\?role=teacher/, /store-detail\.html\?storeId=/, /project-detail\.html\?projectId=/],
    "customer-profile.js": [/recharge-detail\.html/, /verification-detail\.html/],
    "store-detail.js": [/customer-detail\.html\?customerId=/, /\$\{verification \? "verification" : "recharge"\}-detail\.html/],
    "teacher-work-orders.js": [/customer-detail\.html\?/, /\$\{verification \? "verification" : "recharge"\}-detail\.html/],
    "attendance-tracking.js": [/staff-detail\.html\?role=teacher/]
  };
  for (const [file, patterns] of Object.entries(expectations)) {
    const source = read(file);
    for (const pattern of patterns) assert.match(source, pattern, `${file} must retain ${pattern}`);
  }
});

test("each role's generated navigation routes are authorized for that role", () => {
  const auth = read("auth-ui.js");
  const hq = auth.slice(auth.indexOf("hq: new Set"), auth.indexOf("store: new Set"));
  const store = auth.slice(auth.indexOf("store: new Set"), auth.indexOf("teacher: new Set"));
  const teacher = auth.slice(auth.indexOf("teacher: new Set"), auth.indexOf("};", auth.indexOf("teacher: new Set")));
  for (const route of ["index.html", "inactive-customers.html", "low-balance-customers.html", "rating-analysis.html", "daily-report-tracking.html", "attendance-tracking.html", "project-management.html", "store-management.html", "teacher-management.html", "customer-query.html", "recharge-query.html", "verification-query.html"]) assert.match(hq, new RegExp(route.replace(".", "\\.")), `HQ must authorize ${route}`);
  for (const route of ["store-detail.html", "customer-create.html", "recharge-create.html", "product-purchase-create.html", "refund-create.html", "verification-create.html", "customer-query.html", "recharge-query.html", "verification-query.html"]) assert.match(store, new RegExp(route.replace(".", "\\.")), `store must authorize ${route}`);
  for (const route of ["teacher-work-orders.html", "work-calendar.html", "daily-report.html", "attendance.html", "customer-create.html", "recharge-create.html", "product-purchase-create.html", "refund-create.html", "verification-create.html", "verification-experience.html"]) assert.match(teacher, new RegExp(route.replace(".", "\\.")), `teacher must authorize ${route}`);
});

test("the role browser matrix covers every root Web page, including public and redirect pages", () => {
  const auth = read("auth-ui.js");
  const accessSource = auth.slice(auth.indexOf("const access ="), auth.indexOf("let session ="));
  const covered = new Set([...accessSource.matchAll(/"([a-z0-9-]+\.html)"/gi)].map((match) => match[1]));
  ["login.html", "rating.html", "teacher-detail.html"].forEach((page) => covered.add(page));
  assert.deepEqual([...covered].sort(), rootHtml, "no Web page may sit outside the public/redirect/HQ/store/teacher browser matrix");
});
