const { callStaff } = require("../../services/api");
const { waitForStartupSession, requireSession } = require("../../services/session");
function pad(v) { return String(v).padStart(2, "0"); }
function today() { const d = new Date(Date.now() + 8 * 3600000); return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`; }
function monthShift(month, n) { const [y, m] = month.split("-").map(Number), d = new Date(Date.UTC(y, m - 1 + n, 1)); return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}`; }
function cells(month, selected, serverToday) { const [y, m] = month.split("-").map(Number), total = new Date(Date.UTC(y, m, 0)).getUTCDate(), blanks = (new Date(Date.UTC(y, m - 1, 1)).getUTCDay() + 6) % 7, out = Array.from({ length: blanks }, (_, i) => ({ key: `b${i}`, blank: true })); for (let d = 1; d <= total; d += 1) { const date = `${month}-${pad(d)}`; out.push({ key: date, date, day: d, selected: date === selected, today: date === serverToday, future: date > serverToday }); } return out; }
function teacher(row) { const a = row.attendance || null; if (a) { const latitude = Number(a.latitude), longitude = Number(a.longitude); a.latitude = latitude; a.longitude = longitude; a.accuracy = Number(a.accuracy); a.checkedTime = String(a.checkedInAt || "").replace("T", " ").slice(0, 19); a.markers = [{ id: 1, latitude, longitude, title: `${row.teacherName}打卡位置`, width: 28, height: 28 }]; } return { ...row, phone: String(row.phone || ""), attendance: a }; }
Page({
  data: { authorized: false, loading: true, serverToday: "", visibleMonth: "", selectedDate: "", pendingDate: "", canNextMonth: false, calendarCells: [], completed: [], incomplete: [], message: "", error: false, detailOpen: false, detail: {} },
  async onLoad() { this._unloaded = false; const date = today(); this.setData({ serverToday: date, visibleMonth: date.slice(0, 7), selectedDate: date, pendingDate: date, calendarCells: cells(date.slice(0, 7), date, date) }); await waitForStartupSession(); if (this._unloaded || !requireSession(["hq"])) return; this.setData({ authorized: true }); await this.loadDay(date); },
  onUnload() { this._unloaded = true; this._epoch = (this._epoch || 0) + 1; },
  onPullDownRefresh() { this.loadDay(this.data.selectedDate).finally(() => wx.stopPullDownRefresh()); },
  back() { if (getCurrentPages().length > 1) wx.navigateBack(); else wx.reLaunch({ url: "/pages/home/index" }); },
  async loadDay(attendanceDate) { const epoch = this._epoch = (this._epoch || 0) + 1; this.setData({ loading: true, message: "正在读取打卡情况…", error: false, detailOpen: false }); try { const result = await callStaff("getHqAttendanceTrackingDay", { attendanceDate }); if (this._unloaded || epoch !== this._epoch) return; const serverToday = String(result.serverToday || this.data.serverToday), selectedDate = String(result.attendanceDate || attendanceDate), visibleMonth = selectedDate.slice(0, 7); this.setData({ serverToday, selectedDate, pendingDate: selectedDate, visibleMonth, canNextMonth: monthShift(visibleMonth, 1) <= serverToday.slice(0, 7), calendarCells: cells(visibleMonth, selectedDate, serverToday), completed: (result.completed || []).map(teacher), incomplete: (result.incomplete || []).map(teacher), message: "", error: false }); } catch (error) { if (!this._unloaded && epoch === this._epoch) this.setData({ message: error.message || "打卡追踪读取失败", error: true }); } finally { if (!this._unloaded && epoch === this._epoch) this.setData({ loading: false }); } },
  selectDate(event) { const date = String(event.currentTarget.dataset.date || ""); if (date && date <= this.data.serverToday && !this.data.loading) return this.loadDay(date); },
  previousMonth() { if (!this.data.loading) return this.loadDay(`${monthShift(this.data.visibleMonth, -1)}-01`); },
  nextMonth() { const month = monthShift(this.data.visibleMonth, 1); if (!this.data.loading && month <= this.data.serverToday.slice(0, 7)) return this.loadDay(month === this.data.serverToday.slice(0, 7) ? this.data.serverToday : `${month}-01`); },
  chooseMonth(event) { const month = String(event.detail.value || "").slice(0, 7); if (/^\d{4}-\d{2}$/.test(month) && month <= this.data.serverToday.slice(0, 7)) return this.loadDay(month === this.data.serverToday.slice(0, 7) ? this.data.serverToday : `${month}-01`); },
  chooseDate(event) { const date = String(event.detail.value || ""); if (/^\d{4}-\d{2}-\d{2}$/.test(date) && date <= this.data.serverToday) this.setData({ pendingDate: date }); },
  confirmDate() { const date = String(this.data.pendingDate || ""); if (/^\d{4}-\d{2}-\d{2}$/.test(date) && date <= this.data.serverToday && !this.data.loading) return this.loadDay(date); },
  today() { if (!this.data.loading) return this.loadDay(this.data.serverToday); },
  openTeacher(event) { const id = String(event.currentTarget.dataset.id || ""); if (id) wx.navigateTo({ url: `/pages/teacher-detail/index?teacherRef=${encodeURIComponent(id)}` }); },
  openDetail(event) { const id = String(event.currentTarget.dataset.id || ""), detail = this.data.completed.find((row) => row.teacherId === id); if (detail) this.setData({ detailOpen: true, detail }); },
  closeDetail() { this.setData({ detailOpen: false, detail: {} }); },
  openLocation() { const a = this.data.detail.attendance; if (a) wx.openLocation({ latitude: a.latitude, longitude: a.longitude, scale: 18, name: `${this.data.detail.teacherName}打卡位置`, address: `定位精度约 ${a.accuracy} 米` }); }, noop() {}
});
