const { callStaff } = require("../../services/api");
const { waitForStartupSession, requireSession } = require("../../services/session");
const { formatShanghaiTimestamp } = require("../../services/business-time");
function pad(v) { return String(v).padStart(2, "0"); }
function today() { const d = new Date(Date.now() + 8 * 3600000); return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`; }
function monthShift(month, n) { const [y, m] = month.split("-").map(Number), d = new Date(Date.UTC(y, m - 1 + n, 1)); return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}`; }
function cells(month, selected, serverToday) { const [y, m] = month.split("-").map(Number), total = new Date(Date.UTC(y, m, 0)).getUTCDate(), blanks = (new Date(Date.UTC(y, m - 1, 1)).getUTCDay() + 6) % 7, out = Array.from({ length: blanks }, (_, i) => ({ key: `b${i}`, blank: true })); for (let d = 1; d <= total; d += 1) { const date = `${month}-${pad(d)}`; out.push({ key: date, date, day: d, selected: date === selected, today: date === serverToday, future: date > serverToday }); } return out; }
function durationText(seconds) { const value = Number(seconds); if (!Number.isFinite(value) || value < 0) return "—"; const minutes = Math.floor(value / 60), hours = Math.floor(minutes / 60), rest = minutes % 60; if (hours && rest) return `${hours}小时${rest}分钟`; if (hours) return `${hours}小时`; return `${rest}分钟`; }
function punch(row, teacherName, label) { if (!row) return null; const latitude = Number(row.latitude), longitude = Number(row.longitude), placeName = String(row.placeName || ""), formattedAddress = String(row.formattedAddress || ""); return { ...row, latitude, longitude, placeName, formattedAddress, accuracy: Number(row.accuracy), checkedTime: formatShanghaiTimestamp(row.checkedInAt), punchLabel: label, coordinateText: `${latitude.toFixed(6)}, ${longitude.toFixed(6)}`, markers: [{ id: label === "下班打卡" ? 2 : 1, latitude, longitude, title: placeName || `${teacherName}${label}位置`, width: 28, height: 28 }] }; }
function teacher(row) { const clockIn = punch(row.clockIn, row.teacherName, "上班打卡"), clockOut = punch(row.clockOut, row.teacherName, "下班打卡"); return { ...row, phone: String(row.phone || ""), clockIn, clockOut, clockInTime: clockIn?.checkedTime || "—", clockOutTime: clockOut?.checkedTime || "—", workDurationText: durationText(row.workDurationSeconds) }; }
Page({
  data: { authorized: false, loading: true, serverToday: "", visibleMonth: "", selectedDate: "", pendingDate: "", canNextMonth: false, calendarCells: [], completed: [], clockInOnly: [], clockOutOnly: [], missing: [], allTeachers: [], statusGroups: [], message: "", error: false, detailOpen: false, detail: {} },
  async onLoad() { this._unloaded = false; const date = today(); this.setData({ serverToday: date, visibleMonth: date.slice(0, 7), selectedDate: date, pendingDate: date, calendarCells: cells(date.slice(0, 7), date, date) }); await waitForStartupSession(); if (this._unloaded || !requireSession(["hq"])) return; this.setData({ authorized: true }); await this.loadDay(date); },
  onUnload() { this._unloaded = true; this._epoch = (this._epoch || 0) + 1; },
  onPullDownRefresh() { this.loadDay(this.data.selectedDate).finally(() => wx.stopPullDownRefresh()); },
  back() { if (getCurrentPages().length > 1) wx.navigateBack(); else wx.reLaunch({ url: "/pages/home/index" }); },
  async loadDay(attendanceDate) { const epoch = this._epoch = (this._epoch || 0) + 1; this.setData({ loading: true, message: "正在读取上下班打卡情况…", error: false, detailOpen: false }); try { const result = await callStaff("getHqAttendanceTrackingDay", { attendanceDate }); if (this._unloaded || epoch !== this._epoch) return; const serverToday = String(result.serverToday || this.data.serverToday), selectedDate = String(result.attendanceDate || attendanceDate), visibleMonth = selectedDate.slice(0, 7); const completed = (result.completed || []).map(teacher), clockInOnly = (result.clockInOnly || []).map(teacher), clockOutOnly = (result.clockOutOnly || []).map(teacher), missing = (result.missing || result.incomplete || []).map(teacher), allTeachers = [...completed, ...clockInOnly, ...clockOutOnly, ...missing]; const statusGroups = [{ key: "complete", title: "完整打卡", empty: "所选日期暂无完整打卡老师", items: completed }, { key: "clock-in-only", title: "仅上班打卡", empty: "所选日期暂无仅上班打卡老师", items: clockInOnly }, { key: "clock-out-only", title: "仅下班打卡", empty: "所选日期暂无仅下班打卡老师", items: clockOutOnly }, { key: "missing", title: "未打卡", empty: "全部在职老师均已有打卡记录", items: missing }]; this.setData({ serverToday, selectedDate, pendingDate: selectedDate, visibleMonth, canNextMonth: monthShift(visibleMonth, 1) <= serverToday.slice(0, 7), calendarCells: cells(visibleMonth, selectedDate, serverToday), completed, clockInOnly, clockOutOnly, missing, allTeachers, statusGroups, message: "", error: false }); } catch (error) { if (!this._unloaded && epoch === this._epoch) this.setData({ message: error.message || "打卡追踪读取失败", error: true }); } finally { if (!this._unloaded && epoch === this._epoch) this.setData({ loading: false }); } },
  selectDate(event) { const date = String(event.currentTarget.dataset.date || ""); if (date && date <= this.data.serverToday && !this.data.loading) return this.loadDay(date); },
  previousMonth() { if (!this.data.loading) return this.loadDay(`${monthShift(this.data.visibleMonth, -1)}-01`); },
  nextMonth() { const month = monthShift(this.data.visibleMonth, 1); if (!this.data.loading && month <= this.data.serverToday.slice(0, 7)) return this.loadDay(month === this.data.serverToday.slice(0, 7) ? this.data.serverToday : `${month}-01`); },
  chooseMonth(event) { const month = String(event.detail.value || "").slice(0, 7); if (/^\d{4}-\d{2}$/.test(month) && month <= this.data.serverToday.slice(0, 7)) return this.loadDay(month === this.data.serverToday.slice(0, 7) ? this.data.serverToday : `${month}-01`); },
  chooseDate(event) { const date = String(event.detail.value || ""); if (/^\d{4}-\d{2}-\d{2}$/.test(date) && date <= this.data.serverToday) this.setData({ pendingDate: date }); },
  confirmDate() { const date = String(this.data.pendingDate || ""); if (/^\d{4}-\d{2}-\d{2}$/.test(date) && date <= this.data.serverToday && !this.data.loading) return this.loadDay(date); },
  today() { if (!this.data.loading) return this.loadDay(this.data.serverToday); },
  openTeacher(event) { const id = String(event.currentTarget.dataset.id || ""); if (id) wx.navigateTo({ url: `/pages/teacher-detail/index?teacherRef=${encodeURIComponent(id)}` }); },
  openDetail(event) { const id = String(event.currentTarget.dataset.id || ""), kind = String(event.currentTarget.dataset.kind || "clockIn"), person = this.data.allTeachers.find((row) => row.teacherId === id), attendance = person?.[kind]; if (person && attendance) this.setData({ detailOpen: true, detail: { teacherId: person.teacherId, teacherName: person.teacherName, phone: person.phone, kind, attendance } }); },
  closeDetail() { this.setData({ detailOpen: false, detail: {} }); },
  openLocation() { const a = this.data.detail.attendance; if (a) wx.openLocation({ latitude: a.latitude, longitude: a.longitude, scale: 18, name: a.placeName || `${this.data.detail.teacherName}${a.punchLabel}位置`, address: a.formattedAddress || `定位精度约 ${a.accuracy} 米` }); }, noop() {}
});
