-- Execute only after migrations 037 and 038 have committed.
-- CloudBase ExecutePGSql editor users should run the shorter 039-01 through
-- 039-05 files in database/cloudbase-console instead of this combined file.
BEGIN;

DO $$
BEGIN
  IF TO_REGCLASS('public.verification_photos') IS NULL
     OR TO_REGPROCEDURE(
       'public.upsert_verification_extra_photo(bigint,smallint,bigint,character varying,character varying,integer,integer,integer,integer,character)'
     ) IS NULL THEN
    RAISE EXCEPTION 'migrations 037 and 038 must be executed before migration 039';
  END IF;
END;
$$;

-- Direct uploads are represented by short-lived, single-use intents. Object
-- names are generated by the cloud function; browser input is never used in a
-- path. Terminal rows are retained briefly for idempotency and audit.
CREATE TABLE IF NOT EXISTS public.verification_photo_upload_requests (
  request_id VARCHAR(64) PRIMARY KEY,
  verification_id BIGINT NOT NULL REFERENCES public.verification_records(id),
  photo_slot SMALLINT NOT NULL CHECK (photo_slot BETWEEN 2 AND 4),
  actor_account_id BIGINT NOT NULL REFERENCES public.staff_accounts(id),
  status VARCHAR(16) NOT NULL
    CHECK (status IN ('UPLOADING', 'COMMITTED', 'CANCELLED', 'EXPIRED')),
  bucket_id VARCHAR(128) NOT NULL,
  original_object_ref VARCHAR(768) NOT NULL,
  thumbnail_object_ref VARCHAR(768),
  expected_original_bytes INTEGER NOT NULL
    CHECK (expected_original_bytes BETWEEN 4 AND 3145728),
  actual_original_bytes INTEGER,
  image_width INTEGER,
  image_height INTEGER,
  sha256 CHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  cleanup_after TIMESTAMPTZ NOT NULL,
  committed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  objects_cleaned_at TIMESTAMPTZ,
  CHECK (request_id ~ '^[A-Za-z0-9][A-Za-z0-9_-]{15,63}$'),
  CHECK (BTRIM(bucket_id) <> ''),
  CHECK (BTRIM(original_object_ref) <> ''),
  CHECK (thumbnail_object_ref IS NULL OR BTRIM(thumbnail_object_ref) <> ''),
  CHECK (expires_at > created_at),
  CHECK (cleanup_after >= created_at + INTERVAL '3 hours'),
  CHECK (
    (status = 'UPLOADING' AND committed_at IS NULL AND cancelled_at IS NULL)
    OR (status = 'COMMITTED' AND committed_at IS NOT NULL AND cancelled_at IS NULL)
    OR (status = 'CANCELLED' AND committed_at IS NULL AND cancelled_at IS NOT NULL)
    OR (status = 'EXPIRED' AND committed_at IS NULL)
  ),
  CHECK (
    (status <> 'COMMITTED'
      AND actual_original_bytes IS NULL
      AND image_width IS NULL AND image_height IS NULL AND sha256 IS NULL)
    OR
    (status = 'COMMITTED'
      AND actual_original_bytes BETWEEN 4 AND 3145728
      AND image_width BETWEEN 1 AND 10000
      AND image_height BETWEEN 1 AND 10000
      AND sha256 ~ '^[0-9a-f]{64}$')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_verification_photo_upload_one_active_order
  ON public.verification_photo_upload_requests (verification_id)
  WHERE status = 'UPLOADING';

CREATE INDEX IF NOT EXISTS idx_verification_photo_upload_cleanup
  ON public.verification_photo_upload_requests
    (status, expires_at, request_id)
  WHERE status IN ('UPLOADING', 'CANCELLED', 'EXPIRED');

CREATE INDEX IF NOT EXISTS idx_verification_photo_upload_terminal_cleanup
  ON public.verification_photo_upload_requests
    (cleanup_after, request_id)
  WHERE status IN ('CANCELLED', 'EXPIRED') AND objects_cleaned_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_verification_photo_upload_actor
  ON public.verification_photo_upload_requests
    (actor_account_id, verification_id, created_at DESC);

ALTER TABLE public.verification_photo_upload_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.verification_photo_upload_requests FROM PUBLIC;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON TABLE public.verification_photo_upload_requests FROM authenticated;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON TABLE public.verification_photo_upload_requests FROM anon;
  END IF;
END;
$$;

-- New direct EXTRA rows reuse the original object reference for the thumbnail
-- and let CloudBase image processing generate a small preview on demand. Keep
-- the legacy two-object shape valid while old clients are phased out.
ALTER TABLE public.verification_photos
  DROP CONSTRAINT IF EXISTS verification_photos_metadata_v38_check,
  DROP CONSTRAINT IF EXISTS verification_photos_metadata_v39_check;

ALTER TABLE public.verification_photos
  ADD CONSTRAINT verification_photos_metadata_v39_check
    CHECK (
      (photo_kind = 'PROFILE'
       AND original_bytes IS NULL AND thumbnail_bytes IS NULL
       AND image_width IS NULL AND image_height IS NULL AND sha256 IS NULL)
      OR
      (photo_kind = 'FACE'
       AND original_bytes BETWEEN 1 AND 3145728
       AND thumbnail_bytes BETWEEN 1 AND 393216
       AND image_width BETWEEN 1 AND 10000
       AND image_height BETWEEN 1 AND 10000
       AND sha256 ~ '^[0-9a-f]{64}$')
      OR
      (photo_kind = 'EXTRA'
       AND original_bytes BETWEEN 1 AND 3145728
       AND image_width BETWEEN 1 AND 10000
       AND image_height BETWEEN 1 AND 10000
       AND sha256 ~ '^[0-9a-f]{64}$'
       AND (
         (thumbnail_object_ref = original_object_ref AND thumbnail_bytes IS NULL)
         OR
         (thumbnail_object_ref <> original_object_ref
          AND thumbnail_bytes BETWEEN 1 AND 393216)
       ))
    );

CREATE OR REPLACE FUNCTION public.begin_verification_photo_upload(
  p_request_id VARCHAR,
  p_verification_id BIGINT,
  p_photo_slot SMALLINT,
  p_actor_account_id BIGINT,
  p_bucket_id VARCHAR,
  p_original_object_ref VARCHAR,
  p_expected_original_bytes INTEGER,
  p_ttl_seconds INTEGER
)
RETURNS TABLE(
  request_id VARCHAR,
  request_status VARCHAR,
  photo_slot SMALLINT,
  bucket_id VARCHAR,
  original_object_ref VARCHAR,
  expected_original_bytes INTEGER,
  expires_at TIMESTAMPTZ,
  committed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  created_now BOOLEAN,
  request_matches BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
  order_submitter BIGINT;
  order_submitted_at TIMESTAMPTZ;
  existing_request public.verification_photo_upload_requests%ROWTYPE;
  active_request public.verification_photo_upload_requests%ROWTYPE;
  saved_request public.verification_photo_upload_requests%ROWTYPE;
BEGIN
  IF p_photo_slot NOT BETWEEN 2 AND 4 THEN
    RAISE EXCEPTION 'only supplemental photo slots 2 through 4 are writable'
      USING ERRCODE = '22023';
  END IF;
  IF p_expected_original_bytes NOT BETWEEN 4 AND 3145728 THEN
    RAISE EXCEPTION 'direct upload size is invalid' USING ERRCODE = '22023';
  END IF;
  IF p_ttl_seconds NOT BETWEEN 120 AND 900 THEN
    RAISE EXCEPTION 'direct upload ttl is invalid' USING ERRCODE = '22023';
  END IF;
  IF p_request_id !~ '^[A-Za-z0-9][A-Za-z0-9_-]{15,63}$' THEN
    RAISE EXCEPTION 'direct upload request id is invalid' USING ERRCODE = '22023';
  END IF;

  SELECT v.submitted_by_account_id, v.submitted_at
    INTO order_submitter, order_submitted_at
    FROM public.verification_records AS v
   WHERE v.id = p_verification_id
   FOR UPDATE;

  IF order_submitter IS NULL THEN
    RAISE EXCEPTION 'verification order does not exist' USING ERRCODE = 'P0002';
  END IF;
  IF order_submitter <> p_actor_account_id THEN
    RAISE EXCEPTION 'only the verification submitter may upload photo evidence'
      USING ERRCODE = '42501';
  END IF;
  IF CLOCK_TIMESTAMP() >= order_submitted_at + INTERVAL '24 hours' THEN
    RAISE EXCEPTION 'the verification photo upload window has expired'
      USING ERRCODE = '22023';
  END IF;

  UPDATE public.verification_photo_upload_requests AS upload_request
     SET status = 'EXPIRED', updated_at = NOW()
   WHERE upload_request.verification_id = p_verification_id
     AND upload_request.status = 'UPLOADING'
     AND upload_request.expires_at <= CLOCK_TIMESTAMP();

  SELECT upload_request.*
    INTO existing_request
    FROM public.verification_photo_upload_requests AS upload_request
   WHERE upload_request.request_id = p_request_id
   FOR UPDATE;

  IF existing_request.request_id IS NOT NULL THEN
    IF existing_request.verification_id <> p_verification_id
       OR existing_request.photo_slot <> p_photo_slot
       OR existing_request.actor_account_id <> p_actor_account_id
       OR existing_request.expected_original_bytes <> p_expected_original_bytes THEN
      RAISE EXCEPTION 'request id belongs to a different photo upload'
        USING ERRCODE = '23505';
    END IF;
    RETURN QUERY SELECT
      existing_request.request_id, existing_request.status,
      existing_request.photo_slot, existing_request.bucket_id,
      existing_request.original_object_ref,
      existing_request.expected_original_bytes, existing_request.expires_at,
      existing_request.committed_at, existing_request.cancelled_at,
      FALSE, TRUE;
    RETURN;
  END IF;

  SELECT upload_request.*
    INTO active_request
    FROM public.verification_photo_upload_requests AS upload_request
   WHERE upload_request.verification_id = p_verification_id
     AND upload_request.status = 'UPLOADING'
   LIMIT 1
   FOR UPDATE;

  IF active_request.request_id IS NOT NULL THEN
    RETURN QUERY SELECT
      active_request.request_id, active_request.status,
      active_request.photo_slot, active_request.bucket_id,
      active_request.original_object_ref,
      active_request.expected_original_bytes, active_request.expires_at,
      active_request.committed_at, active_request.cancelled_at,
      FALSE, FALSE;
    RETURN;
  END IF;

  IF (
    SELECT COUNT(*)
      FROM public.verification_photo_upload_requests AS recent_request
     WHERE recent_request.verification_id = p_verification_id
       AND recent_request.actor_account_id = p_actor_account_id
       AND recent_request.created_at >= CLOCK_TIMESTAMP() - INTERVAL '1 hour'
  ) >= 30 THEN
    RAISE EXCEPTION 'PHOTO_UPLOAD_RATE_LIMITED: too many upload requests for this order'
      USING ERRCODE = '54000';
  END IF;

  IF BTRIM(COALESCE(p_bucket_id, '')) = ''
     OR p_original_object_ref NOT LIKE
       ('pg://' || p_bucket_id || '/records/' || p_verification_id::TEXT
        || '/slot-' || p_photo_slot::TEXT || '/direct-%.jpg') THEN
    RAISE EXCEPTION 'server-generated photo object reference is invalid'
      USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.verification_photo_upload_requests
    (request_id, verification_id, photo_slot, actor_account_id, status,
     bucket_id, original_object_ref, expected_original_bytes, expires_at,
     cleanup_after)
  VALUES
    (p_request_id, p_verification_id, p_photo_slot, p_actor_account_id,
     'UPLOADING', p_bucket_id, p_original_object_ref,
     p_expected_original_bytes,
     LEAST(
       CLOCK_TIMESTAMP() + (p_ttl_seconds * INTERVAL '1 second'),
       order_submitted_at + INTERVAL '24 hours'
     ),
     CLOCK_TIMESTAMP() + INTERVAL '3 hours')
  RETURNING * INTO saved_request;

  RETURN QUERY SELECT
    saved_request.request_id, saved_request.status,
    saved_request.photo_slot, saved_request.bucket_id,
    saved_request.original_object_ref, saved_request.expected_original_bytes,
    saved_request.expires_at, saved_request.committed_at,
    saved_request.cancelled_at, TRUE, TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.commit_verification_photo_upload(
  p_request_id VARCHAR,
  p_verification_id BIGINT,
  p_actor_account_id BIGINT,
  p_actual_original_bytes INTEGER,
  p_image_width INTEGER,
  p_image_height INTEGER,
  p_sha256 CHAR(64)
)
RETURNS TABLE(
  request_id VARCHAR,
  request_status VARCHAR,
  photo_slot SMALLINT,
  committed_now BOOLEAN,
  old_original_object_ref TEXT,
  old_thumbnail_object_ref TEXT,
  photo_id BIGINT,
  original_bytes INTEGER,
  image_width INTEGER,
  image_height INTEGER,
  sha256 CHAR(64),
  uploaded_at TIMESTAMPTZ,
  committed_at TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
  order_submitter BIGINT;
  order_submitted_at TIMESTAMPTZ;
  upload_request public.verification_photo_upload_requests%ROWTYPE;
  saved_photo public.verification_photos%ROWTYPE;
  old_original TEXT;
  old_thumbnail TEXT;
BEGIN
  SELECT v.submitted_by_account_id, v.submitted_at
    INTO order_submitter, order_submitted_at
    FROM public.verification_records AS v
   WHERE v.id = p_verification_id
   FOR UPDATE;

  IF order_submitter IS NULL THEN
    RAISE EXCEPTION 'verification order does not exist' USING ERRCODE = 'P0002';
  END IF;
  IF order_submitter <> p_actor_account_id THEN
    RAISE EXCEPTION 'only the verification submitter may upload photo evidence'
      USING ERRCODE = '42501';
  END IF;

  SELECT pending.*
    INTO upload_request
    FROM public.verification_photo_upload_requests AS pending
   WHERE pending.request_id = p_request_id
   FOR UPDATE;

  IF upload_request.request_id IS NULL
     OR upload_request.verification_id <> p_verification_id
     OR upload_request.actor_account_id <> p_actor_account_id THEN
    RAISE EXCEPTION 'direct upload request does not exist' USING ERRCODE = 'P0002';
  END IF;

  IF upload_request.status = 'COMMITTED' THEN
    SELECT photo.*
      INTO saved_photo
      FROM public.verification_photos AS photo
     WHERE photo.verification_id = p_verification_id
       AND photo.photo_slot = upload_request.photo_slot
       AND photo.original_object_ref = upload_request.original_object_ref
     LIMIT 1;
    RETURN QUERY SELECT
      upload_request.request_id, upload_request.status,
      upload_request.photo_slot, FALSE, NULL::TEXT, NULL::TEXT,
      saved_photo.id, upload_request.actual_original_bytes,
      upload_request.image_width, upload_request.image_height,
      upload_request.sha256, upload_request.committed_at,
      upload_request.committed_at;
    RETURN;
  END IF;

  IF upload_request.status IN ('CANCELLED', 'EXPIRED') THEN
    RETURN QUERY SELECT
      upload_request.request_id, upload_request.status,
      upload_request.photo_slot, FALSE, NULL::TEXT, NULL::TEXT,
      NULL::BIGINT, NULL::INTEGER, NULL::INTEGER, NULL::INTEGER,
      NULL::CHAR(64), NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  IF upload_request.expires_at <= CLOCK_TIMESTAMP()
     OR CLOCK_TIMESTAMP() >= order_submitted_at + INTERVAL '24 hours' THEN
    UPDATE public.verification_photo_upload_requests AS pending
       SET status = 'EXPIRED', updated_at = NOW()
     WHERE pending.request_id = p_request_id
     RETURNING * INTO upload_request;
    RETURN QUERY SELECT
      upload_request.request_id, upload_request.status,
      upload_request.photo_slot, FALSE, NULL::TEXT, NULL::TEXT,
      NULL::BIGINT, NULL::INTEGER, NULL::INTEGER, NULL::INTEGER,
      NULL::CHAR(64), NULL::TIMESTAMPTZ, NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  IF p_actual_original_bytes IS NULL
     OR p_image_width IS NULL OR p_image_height IS NULL OR p_sha256 IS NULL
     OR p_actual_original_bytes <> upload_request.expected_original_bytes
     OR p_actual_original_bytes NOT BETWEEN 4 AND 3145728
     OR p_image_width NOT BETWEEN 1 AND 10000
     OR p_image_height NOT BETWEEN 1 AND 10000
     OR p_sha256 !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'verified direct upload metadata is invalid'
      USING ERRCODE = '22023';
  END IF;

  SELECT photo.original_object_ref, photo.thumbnail_object_ref
    INTO old_original, old_thumbnail
    FROM public.verification_photos AS photo
   WHERE photo.verification_id = p_verification_id
     AND photo.photo_slot = upload_request.photo_slot
   FOR UPDATE;

  INSERT INTO public.verification_photos
    (verification_id, photo_slot, photo_kind, original_object_ref,
     thumbnail_object_ref, original_bytes, thumbnail_bytes,
     image_width, image_height, sha256, uploaded_by_account_id)
  VALUES
    (p_verification_id, upload_request.photo_slot, 'EXTRA',
     upload_request.original_object_ref, upload_request.original_object_ref,
     p_actual_original_bytes, NULL, p_image_width, p_image_height,
     p_sha256, p_actor_account_id)
  ON CONFLICT (verification_id, photo_slot) DO UPDATE
     SET original_object_ref = EXCLUDED.original_object_ref,
         thumbnail_object_ref = EXCLUDED.thumbnail_object_ref,
         original_bytes = EXCLUDED.original_bytes,
         thumbnail_bytes = EXCLUDED.thumbnail_bytes,
         image_width = EXCLUDED.image_width,
         image_height = EXCLUDED.image_height,
         sha256 = EXCLUDED.sha256,
         updated_at = NOW()
  RETURNING * INTO saved_photo;

  INSERT INTO public.verification_photo_events
    (verification_id, photo_slot, event_type, actor_account_id)
  VALUES
    (p_verification_id, upload_request.photo_slot,
     CASE WHEN old_original IS NULL THEN 'UPLOAD' ELSE 'REPLACE' END,
     p_actor_account_id);

  UPDATE public.verification_photo_upload_requests AS pending
     SET status = 'COMMITTED',
         actual_original_bytes = p_actual_original_bytes,
         image_width = p_image_width,
         image_height = p_image_height,
         sha256 = p_sha256,
         committed_at = NOW(),
         updated_at = NOW()
   WHERE pending.request_id = p_request_id
   RETURNING * INTO upload_request;

  RETURN QUERY SELECT
    upload_request.request_id, upload_request.status,
    upload_request.photo_slot, TRUE, old_original, old_thumbnail,
    saved_photo.id, saved_photo.original_bytes,
    saved_photo.image_width, saved_photo.image_height, saved_photo.sha256,
    saved_photo.updated_at, upload_request.committed_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.cancel_verification_photo_upload(
  p_request_id VARCHAR,
  p_verification_id BIGINT,
  p_actor_account_id BIGINT
)
RETURNS TABLE(
  request_id VARCHAR,
  request_status VARCHAR,
  photo_slot SMALLINT,
  expected_original_bytes INTEGER,
  expires_at TIMESTAMPTZ,
  committed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancelled_now BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
  order_submitter BIGINT;
  upload_request public.verification_photo_upload_requests%ROWTYPE;
  did_cancel BOOLEAN := FALSE;
BEGIN
  SELECT v.submitted_by_account_id
    INTO order_submitter
    FROM public.verification_records AS v
   WHERE v.id = p_verification_id
   FOR UPDATE;

  IF order_submitter IS NULL THEN
    RAISE EXCEPTION 'verification order does not exist' USING ERRCODE = 'P0002';
  END IF;
  IF order_submitter <> p_actor_account_id THEN
    RAISE EXCEPTION 'only the verification submitter may cancel photo uploads'
      USING ERRCODE = '42501';
  END IF;

  SELECT pending.*
    INTO upload_request
    FROM public.verification_photo_upload_requests AS pending
   WHERE pending.request_id = p_request_id
   FOR UPDATE;

  IF upload_request.request_id IS NULL
     OR upload_request.verification_id <> p_verification_id
     OR upload_request.actor_account_id <> p_actor_account_id THEN
    RAISE EXCEPTION 'direct upload request does not exist' USING ERRCODE = 'P0002';
  END IF;

  IF upload_request.status = 'UPLOADING' THEN
    IF upload_request.expires_at <= CLOCK_TIMESTAMP() THEN
      UPDATE public.verification_photo_upload_requests AS pending
         SET status = 'EXPIRED', updated_at = NOW()
       WHERE pending.request_id = p_request_id
       RETURNING * INTO upload_request;
    ELSE
      UPDATE public.verification_photo_upload_requests AS pending
         SET status = 'CANCELLED', cancelled_at = NOW(), updated_at = NOW()
       WHERE pending.request_id = p_request_id
       RETURNING * INTO upload_request;
      did_cancel := TRUE;
    END IF;
  END IF;

  RETURN QUERY SELECT
    upload_request.request_id, upload_request.status,
    upload_request.photo_slot, upload_request.expected_original_bytes,
    upload_request.expires_at, upload_request.committed_at,
    upload_request.cancelled_at, did_cancel;
END;
$$;

REVOKE ALL ON FUNCTION public.begin_verification_photo_upload(
  VARCHAR, BIGINT, SMALLINT, BIGINT, VARCHAR, VARCHAR, INTEGER, INTEGER
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.commit_verification_photo_upload(
  VARCHAR, BIGINT, BIGINT, INTEGER, INTEGER, INTEGER, CHAR
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cancel_verification_photo_upload(
  VARCHAR, BIGINT, BIGINT
) FROM PUBLIC;

COMMENT ON TABLE public.verification_photo_upload_requests IS
  'Migration 039: short-lived, single-active direct upload intents for verification supplemental photos.';
COMMENT ON FUNCTION public.begin_verification_photo_upload(
  VARCHAR, BIGINT, SMALLINT, BIGINT, VARCHAR, VARCHAR, INTEGER, INTEGER
) IS 'Migration 039: idempotently reserves one server-generated upload object per verification order.';
COMMENT ON FUNCTION public.commit_verification_photo_upload(
  VARCHAR, BIGINT, BIGINT, INTEGER, INTEGER, INTEGER, CHAR
) IS 'Migration 039: atomically binds a server-inspected JPEG and closes its upload intent.';

COMMIT;
