BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.retail_product_purchase_code_seq START WITH 1;

CREATE TABLE IF NOT EXISTS public.retail_product_purchase_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_code TEXT NOT NULL DEFAULT (
    'PP' || TO_CHAR(CLOCK_TIMESTAMP() AT TIME ZONE 'Asia/Shanghai', 'YYYYMMDD') ||
    LPAD(NEXTVAL('public.retail_product_purchase_code_seq')::text, 6, '0')
  ),
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE RESTRICT,
  teacher_id BIGINT REFERENCES public.teachers(id) ON DELETE RESTRICT,
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  retail_product_id BIGINT NOT NULL REFERENCES public.retail_products(id) ON DELETE RESTRICT,
  unit_count INTEGER NOT NULL,
  record_status TEXT NOT NULL DEFAULT 'PENDING',
  submitted_by_account_id BIGINT NOT NULL REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  message TEXT NOT NULL DEFAULT '',
  idempotency_key TEXT NOT NULL,
  product_code_snapshot TEXT NOT NULL,
  product_name_snapshot TEXT NOT NULL,
  reviewed_by_account_id BIGINT REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  review_note TEXT NOT NULL DEFAULT '',
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_retail_product_purchase_code UNIQUE (purchase_code),
  CONSTRAINT uq_retail_product_purchase_idempotency UNIQUE (idempotency_key),
  CONSTRAINT ck_retail_product_purchase_count CHECK (unit_count BETWEEN 1 AND 999),
  CONSTRAINT ck_retail_product_purchase_status CHECK (record_status IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT ck_retail_product_purchase_message CHECK (CHAR_LENGTH(message) <= 500),
  CONSTRAINT ck_retail_product_purchase_review_note CHECK (CHAR_LENGTH(review_note) <= 1000),
  CONSTRAINT ck_retail_product_purchase_snapshot CHECK (
    BTRIM(product_code_snapshot) <> '' AND BTRIM(product_name_snapshot) <> ''
  ),
  CONSTRAINT ck_retail_product_purchase_review_state CHECK (
    (record_status = 'PENDING' AND reviewed_by_account_id IS NULL AND reviewed_at IS NULL)
    OR
    (record_status IN ('APPROVED', 'REJECTED') AND reviewed_by_account_id IS NOT NULL AND reviewed_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_retail_product_purchase_customer_status
  ON public.retail_product_purchase_records (customer_id, record_status, retail_product_id, submitted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_retail_product_purchase_review
  ON public.retail_product_purchase_records (record_status, submitted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_retail_product_purchase_store
  ON public.retail_product_purchase_records (store_id, submitted_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_retail_product_purchase_teacher
  ON public.retail_product_purchase_records (teacher_id, submitted_at DESC, id DESC)
  WHERE teacher_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.validate_retail_product_purchase_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  selected_product public.retail_products%ROWTYPE;
  selected_customer public.customers%ROWTYPE;
  submitter public.staff_accounts%ROWTYPE;
  bound_teacher public.teachers%ROWTYPE;
BEGIN
  SELECT * INTO selected_product FROM public.retail_products WHERE id = NEW.retail_product_id FOR KEY SHARE;
  IF NOT FOUND OR selected_product.product_status <> 'ACTIVE' THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_PRODUCT_NOT_ACTIVE';
  END IF;
  SELECT * INTO selected_customer FROM public.customers WHERE id = NEW.customer_id FOR KEY SHARE;
  IF NOT FOUND OR selected_customer.customer_status <> 'ACTIVE' OR selected_customer.created_store_id <> NEW.store_id THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_CUSTOMER_SCOPE_INVALID';
  END IF;
  SELECT * INTO submitter FROM public.staff_accounts WHERE id = NEW.submitted_by_account_id FOR KEY SHARE;
  IF NOT FOUND OR submitter.account_status <> 'ACTIVE' OR submitter.role_code NOT IN ('store', 'teacher') THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_SUBMITTER_INVALID';
  END IF;
  IF submitter.role_code = 'teacher' THEN
    SELECT * INTO bound_teacher FROM public.teachers
     WHERE staff_account_id = submitter.id AND teacher_status = 'ACTIVE' FOR KEY SHARE;
    IF NOT FOUND OR NEW.teacher_id IS DISTINCT FROM bound_teacher.id THEN
      RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_TEACHER_BINDING_INVALID';
    END IF;
  ELSIF NEW.teacher_id IS NOT NULL THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_STORE_TEACHER_MUST_BE_EMPTY';
  END IF;
  NEW.product_code_snapshot := selected_product.product_code;
  NEW.product_name_snapshot := selected_product.product_name;
  NEW.record_status := 'PENDING';
  NEW.reviewed_by_account_id := NULL;
  NEW.reviewed_at := NULL;
  NEW.review_note := '';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_062_validate_retail_product_purchase_insert ON public.retail_product_purchase_records;
CREATE TRIGGER trg_062_validate_retail_product_purchase_insert
BEFORE INSERT ON public.retail_product_purchase_records
FOR EACH ROW EXECUTE FUNCTION public.validate_retail_product_purchase_insert();

CREATE OR REPLACE FUNCTION public.prevent_retail_product_purchase_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE reviewer public.staff_accounts%ROWTYPE;
BEGIN
  IF NEW.store_id IS DISTINCT FROM OLD.store_id
     OR NEW.teacher_id IS DISTINCT FROM OLD.teacher_id
     OR NEW.customer_id IS DISTINCT FROM OLD.customer_id
     OR NEW.retail_product_id IS DISTINCT FROM OLD.retail_product_id
     OR NEW.unit_count IS DISTINCT FROM OLD.unit_count
     OR NEW.submitted_by_account_id IS DISTINCT FROM OLD.submitted_by_account_id
     OR NEW.message IS DISTINCT FROM OLD.message
     OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
     OR NEW.product_code_snapshot IS DISTINCT FROM OLD.product_code_snapshot
     OR NEW.product_name_snapshot IS DISTINCT FROM OLD.product_name_snapshot
     OR NEW.submitted_at IS DISTINCT FROM OLD.submitted_at THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_IMMUTABLE';
  END IF;
  IF OLD.record_status <> 'PENDING' OR NEW.record_status NOT IN ('APPROVED', 'REJECTED') THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_STATE_INVALID';
  END IF;
  SELECT * INTO reviewer
    FROM public.staff_accounts
   WHERE id = NEW.reviewed_by_account_id
   FOR KEY SHARE;
  IF NOT FOUND OR reviewer.role_code <> 'hq' OR reviewer.account_status <> 'ACTIVE' THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_REVIEWER_FORBIDDEN';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_062_prevent_retail_product_purchase_mutation ON public.retail_product_purchase_records;
CREATE TRIGGER trg_062_prevent_retail_product_purchase_mutation
BEFORE UPDATE ON public.retail_product_purchase_records
FOR EACH ROW EXECUTE FUNCTION public.prevent_retail_product_purchase_mutation();

CREATE OR REPLACE FUNCTION public.prevent_retail_product_purchase_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_DELETE_FORBIDDEN';
END;
$$;

DROP TRIGGER IF EXISTS trg_062_prevent_retail_product_purchase_delete ON public.retail_product_purchase_records;
CREATE TRIGGER trg_062_prevent_retail_product_purchase_delete
BEFORE DELETE ON public.retail_product_purchase_records
FOR EACH ROW EXECUTE FUNCTION public.prevent_retail_product_purchase_delete();

CREATE OR REPLACE FUNCTION public.review_retail_product_purchase(
  p_record_id BIGINT, p_reviewer_account_id BIGINT, p_decision TEXT, p_note TEXT
)
RETURNS TABLE(record_id BIGINT, purchase_code TEXT, record_status TEXT, reviewed_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE reviewer public.staff_accounts%ROWTYPE;
BEGIN
  SELECT * INTO reviewer FROM public.staff_accounts WHERE id = p_reviewer_account_id FOR KEY SHARE;
  IF NOT FOUND OR reviewer.role_code <> 'hq' OR reviewer.account_status <> 'ACTIVE' THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_REVIEWER_FORBIDDEN';
  END IF;
  IF UPPER(BTRIM(COALESCE(p_decision, ''))) NOT IN ('APPROVED', 'REJECTED') THEN
    RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_DECISION_INVALID';
  END IF;
  RETURN QUERY
  UPDATE public.retail_product_purchase_records purchase
     SET record_status = UPPER(BTRIM(p_decision)),
         reviewed_by_account_id = reviewer.id,
         review_note = LEFT(COALESCE(p_note, ''), 1000),
         reviewed_at = NOW(), updated_at = NOW()
   WHERE purchase.id = p_record_id AND purchase.record_status = 'PENDING'
  RETURNING purchase.id, purchase.purchase_code, purchase.record_status, purchase.reviewed_at;
  IF NOT FOUND THEN RAISE EXCEPTION 'RETAIL_PRODUCT_PURCHASE_NOT_PENDING'; END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.review_retail_product_purchase(BIGINT, BIGINT, TEXT, TEXT) FROM PUBLIC;
ALTER TABLE public.retail_product_purchase_records ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.retail_product_purchase_records IS
  'Independent physical/retail product purchase applications submitted by store or teacher accounts and reviewed by headquarters.';

COMMIT;
