BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.retail_product_code_seq START WITH 1;

CREATE OR REPLACE FUNCTION public.next_retail_product_code()
RETURNS TEXT
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  code_number BIGINT;
BEGIN
  code_number := nextval('public.retail_product_code_seq');
  RETURN 'PDT' || LPAD(code_number::TEXT, GREATEST(3, LENGTH(code_number::TEXT)), '0');
END;
$$;

CREATE TABLE IF NOT EXISTS public.retail_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_code TEXT NOT NULL DEFAULT public.next_retail_product_code(),
  product_name TEXT NOT NULL,
  product_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  idempotency_key VARCHAR(64),
  created_by_staff_account_id BIGINT REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  updated_by_staff_account_id BIGINT REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_retail_products_name_not_blank CHECK (BTRIM(product_name) <> ''),
  CONSTRAINT ck_retail_products_status CHECK (product_status IN ('ACTIVE', 'ARCHIVED')),
  CONSTRAINT uq_retail_products_code UNIQUE (product_code)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_retail_products_normalized_name
  ON public.retail_products (LOWER(BTRIM(product_name)));
CREATE UNIQUE INDEX IF NOT EXISTS uq_retail_products_idempotency_key
  ON public.retail_products (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_retail_products_status_id
  ON public.retail_products (product_status, id);

CREATE TABLE IF NOT EXISTS public.retail_product_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retail_product_id BIGINT NOT NULL REFERENCES public.retail_products(id) ON DELETE RESTRICT,
  previous_status VARCHAR(16) NOT NULL,
  current_status VARCHAR(16) NOT NULL,
  changed_by_staff_account_id BIGINT REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_retail_product_history_previous_status CHECK (previous_status IN ('ACTIVE', 'ARCHIVED')),
  CONSTRAINT ck_retail_product_history_current_status CHECK (current_status IN ('ACTIVE', 'ARCHIVED')),
  CONSTRAINT ck_retail_product_history_status_changed CHECK (previous_status <> current_status)
);
CREATE INDEX IF NOT EXISTS idx_retail_product_status_history_product_time
  ON public.retail_product_status_history (retail_product_id, changed_at DESC, id DESC);

CREATE OR REPLACE FUNCTION public.audit_retail_product_status_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.product_status IS DISTINCT FROM OLD.product_status THEN
    INSERT INTO public.retail_product_status_history
      (retail_product_id, previous_status, current_status, changed_by_staff_account_id)
    VALUES
      (NEW.id, OLD.product_status, NEW.product_status, NEW.updated_by_staff_account_id);
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_060_audit_retail_product_status ON public.retail_products;
CREATE TRIGGER trg_060_audit_retail_product_status
AFTER UPDATE OF product_status ON public.retail_products
FOR EACH ROW EXECUTE FUNCTION public.audit_retail_product_status_change();

CREATE OR REPLACE FUNCTION public.prevent_retail_product_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'RETAIL_PRODUCT_DELETE_FORBIDDEN: archive the product instead';
END;
$$;
DROP TRIGGER IF EXISTS trg_060_prevent_retail_product_delete ON public.retail_products;
CREATE TRIGGER trg_060_prevent_retail_product_delete
BEFORE DELETE ON public.retail_products
FOR EACH ROW EXECUTE FUNCTION public.prevent_retail_product_delete();

COMMENT ON TABLE public.retail_products IS
  'Independent topical/retail product master. Service projects remain in public.products.';
COMMENT ON COLUMN public.retail_products.product_code IS
  'Database-generated immutable retail product code, for example PDT001.';
COMMENT ON COLUMN public.retail_products.product_status IS
  'ACTIVE or ARCHIVED. Rows are never deleted.';

COMMIT;
