BEGIN;

CREATE TABLE IF NOT EXISTS public.recharge_product_gifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recharge_id BIGINT NOT NULL REFERENCES public.recharge_records(id) ON DELETE RESTRICT,
  retail_product_id BIGINT NOT NULL REFERENCES public.retail_products(id) ON DELETE RESTRICT,
  display_order SMALLINT NOT NULL,
  unit_count INTEGER NOT NULL,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE RESTRICT,
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  teacher_id BIGINT REFERENCES public.teachers(id) ON DELETE RESTRICT,
  product_code_snapshot TEXT NOT NULL,
  product_name_snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_recharge_product_gifts_display_order CHECK (display_order BETWEEN 1 AND 20),
  CONSTRAINT ck_recharge_product_gifts_unit_count CHECK (unit_count BETWEEN 1 AND 999),
  CONSTRAINT ck_recharge_product_gifts_code_not_blank CHECK (BTRIM(product_code_snapshot) <> ''),
  CONSTRAINT ck_recharge_product_gifts_name_not_blank CHECK (BTRIM(product_name_snapshot) <> ''),
  CONSTRAINT uq_recharge_product_gifts_product UNIQUE (recharge_id, retail_product_id),
  CONSTRAINT uq_recharge_product_gifts_order UNIQUE (recharge_id, display_order)
);

CREATE INDEX IF NOT EXISTS idx_recharge_product_gifts_recharge_order ON public.recharge_product_gifts (recharge_id, display_order, id);
CREATE INDEX IF NOT EXISTS idx_recharge_product_gifts_customer_time ON public.recharge_product_gifts (customer_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_recharge_product_gifts_store_time ON public.recharge_product_gifts (store_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_recharge_product_gifts_teacher_time ON public.recharge_product_gifts (teacher_id, created_at DESC, id DESC) WHERE teacher_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.validate_recharge_product_gift()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  parent_record public.recharge_records%ROWTYPE;
  retail_product public.retail_products%ROWTYPE;
BEGIN
  SELECT * INTO parent_record FROM public.recharge_records WHERE id = NEW.recharge_id FOR KEY SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'RECHARGE_PRODUCT_GIFT_PARENT_NOT_FOUND'; END IF;
  IF parent_record.recharge_type <> 'NEW' THEN RAISE EXCEPTION 'RECHARGE_PRODUCT_GIFT_RECHARGE_ONLY'; END IF;
  IF NEW.store_id IS DISTINCT FROM parent_record.store_id
     OR NEW.customer_id IS DISTINCT FROM parent_record.customer_id
     OR NEW.teacher_id IS DISTINCT FROM parent_record.teacher_id THEN
    RAISE EXCEPTION 'RECHARGE_PRODUCT_GIFT_SCOPE_MISMATCH';
  END IF;
  SELECT * INTO retail_product FROM public.retail_products WHERE id = NEW.retail_product_id FOR KEY SHARE;
  IF NOT FOUND OR retail_product.product_status <> 'ACTIVE' THEN
    RAISE EXCEPTION 'RECHARGE_PRODUCT_GIFT_PRODUCT_NOT_ACTIVE';
  END IF;
  NEW.product_code_snapshot := retail_product.product_code;
  NEW.product_name_snapshot := retail_product.product_name;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_061_validate_recharge_product_gift ON public.recharge_product_gifts;
CREATE TRIGGER trg_061_validate_recharge_product_gift BEFORE INSERT ON public.recharge_product_gifts
FOR EACH ROW EXECUTE FUNCTION public.validate_recharge_product_gift();

CREATE OR REPLACE FUNCTION public.prevent_recharge_product_gift_mutation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'RECHARGE_PRODUCT_GIFT_IMMUTABLE';
END;
$$;
DROP TRIGGER IF EXISTS trg_061_prevent_recharge_product_gift_update ON public.recharge_product_gifts;
CREATE TRIGGER trg_061_prevent_recharge_product_gift_update BEFORE UPDATE ON public.recharge_product_gifts
FOR EACH ROW EXECUTE FUNCTION public.prevent_recharge_product_gift_mutation();
DROP TRIGGER IF EXISTS trg_061_prevent_recharge_product_gift_delete ON public.recharge_product_gifts;
CREATE TRIGGER trg_061_prevent_recharge_product_gift_delete BEFORE DELETE ON public.recharge_product_gifts
FOR EACH ROW EXECUTE FUNCTION public.prevent_recharge_product_gift_mutation();

ALTER TABLE public.recharge_product_gifts ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.recharge_product_gifts IS 'Optional immutable retail-product gift lines submitted atomically with a NEW recharge application.';
COMMENT ON COLUMN public.recharge_product_gifts.teacher_id IS 'Same validated business teacher as the parent recharge; nullable only when the store recharge did not select a teacher.';
COMMENT ON COLUMN public.recharge_product_gifts.product_code_snapshot IS 'Retail product code snapshot captured at recharge submission.';
COMMENT ON COLUMN public.recharge_product_gifts.product_name_snapshot IS 'Retail product name snapshot captured at recharge submission.';

COMMIT;
