-- Migration 066: split face-verified verification into a short BLE
-- qualification, a one-time device authorization, and the existing atomic
-- verification writer.  Merely opening, closing or retrying the QR/BLE window
-- never consumes customer balance or teacher experience quota.

BEGIN;

DO $$
BEGIN
  IF TO_REGCLASS('public.verification_records') IS NULL
     OR TO_REGCLASS('public.verification_photo_drafts') IS NULL
     OR TO_REGCLASS('public.staff_accounts') IS NULL
     OR TO_REGCLASS('public.products') IS NULL THEN
    RAISE EXCEPTION 'migration 066 prerequisites are missing; execute migrations through 065 first';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    RAISE EXCEPTION 'migration 066 requires the CloudBase service_role';
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.verification_ble_qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qualification_token VARCHAR(48) NOT NULL UNIQUE,
  verification_type VARCHAR(16) NOT NULL
    CHECK (verification_type IN ('NORMAL', 'EXPERIENCE')),
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE RESTRICT,
  teacher_id BIGINT REFERENCES public.teachers(id) ON DELETE RESTRICT,
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  unit_count INTEGER NOT NULL CHECK (unit_count BETWEEN 1 AND 999),
  submitted_by_account_id BIGINT NOT NULL
    REFERENCES public.staff_accounts(id) ON DELETE RESTRICT,
  message TEXT NOT NULL DEFAULT '' CHECK (CHAR_LENGTH(message) <= 500),
  face_request_id VARCHAR(128) NOT NULL,
  face_evidence_token VARCHAR(64) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL UNIQUE,
  expected_device_type VARCHAR(128) NOT NULL
    CHECK (expected_device_type ~ '^[a-z0-9]+$'),
  qualification_status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
    CHECK (qualification_status IN ('PENDING', 'AUTHORIZED', 'COMPLETED', 'EXPIRED', 'CANCELLED')),
  expires_at TIMESTAMPTZ NOT NULL,
  verification_id BIGINT UNIQUE REFERENCES public.verification_records(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '90 seconds'),
  CHECK ((qualification_status = 'COMPLETED') = (verification_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_verification_ble_qualification_actor
  ON public.verification_ble_qualifications
  (submitted_by_account_id, store_id, qualification_status, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_verification_ble_qualification_expiry
  ON public.verification_ble_qualifications
  (qualification_status, expires_at);

CREATE TABLE IF NOT EXISTS public.verification_ble_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qr_sn VARCHAR(32) NOT NULL UNIQUE CHECK (qr_sn ~ '^NCM[0-9A-F]{11}$'),
  device_id VARCHAR(128) NOT NULL UNIQUE,
  device_type VARCHAR(128) NOT NULL CHECK (device_type ~ '^[a-z0-9]+$'),
  ble_name VARCHAR(64) NOT NULL,
  pairing_code_hash CHAR(64) NOT NULL CHECK (pairing_code_hash ~ '^[0-9a-f]{64}$'),
  device_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
    CHECK (device_status IN ('ACTIVE', 'DISABLED', 'RETIRED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (device_id = qr_sn),
  CHECK (ble_name = 'NCM-' || RIGHT(qr_sn, 6))
);

CREATE TABLE IF NOT EXISTS public.verification_ble_authorizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  authorization_token VARCHAR(48) NOT NULL UNIQUE,
  qualification_id BIGINT NOT NULL UNIQUE
    REFERENCES public.verification_ble_qualifications(id) ON DELETE RESTRICT,
  qr_sn VARCHAR(32) NOT NULL CHECK (qr_sn ~ '^NCM[0-9A-F]{11}$'),
  qr_code_hash CHAR(64) NOT NULL CHECK (qr_code_hash ~ '^[0-9a-f]{64}$'),
  device_id VARCHAR(128) NOT NULL,
  device_type VARCHAR(128) NOT NULL CHECK (device_type ~ '^[a-z0-9]+$'),
  nonce CHAR(32) NOT NULL CHECK (nonce ~ '^[0-9a-fA-F]{32}$'),
  unit_count INTEGER NOT NULL CHECK (unit_count BETWEEN 1 AND 999),
  issued_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  signature_hash CHAR(64) NOT NULL CHECK (signature_hash ~ '^[0-9a-f]{64}$'),
  authorization_status VARCHAR(24) NOT NULL DEFAULT 'ISSUED'
    CHECK (authorization_status IN ('ISSUED', 'DEVICE_WORKING', 'FINALIZED', 'EXPIRED', 'FAILED')),
  verification_id BIGINT UNIQUE REFERENCES public.verification_records(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (device_id, nonce),
  CHECK (expires_at > issued_at AND expires_at <= issued_at + INTERVAL '30 seconds'),
  CHECK ((authorization_status = 'FINALIZED') = (verification_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_verification_ble_authorization_qualification
  ON public.verification_ble_authorizations
  (qualification_id, authorization_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_verification_ble_authorization_expiry
  ON public.verification_ble_authorizations
  (authorization_status, expires_at);

ALTER TABLE public.verification_ble_qualifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_ble_authorizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_ble_devices ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.verification_ble_qualifications
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.verification_ble_authorizations
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.verification_ble_devices
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.verification_ble_qualifications_id_seq
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.verification_ble_authorizations_id_seq
  FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.verification_ble_devices_id_seq
  FROM PUBLIC, anon, authenticated;

GRANT ALL PRIVILEGES ON TABLE public.verification_ble_qualifications TO service_role;
GRANT ALL PRIVILEGES ON TABLE public.verification_ble_authorizations TO service_role;
GRANT ALL PRIVILEGES ON TABLE public.verification_ble_devices TO service_role;
GRANT ALL PRIVILEGES ON SEQUENCE public.verification_ble_qualifications_id_seq TO service_role;
GRANT ALL PRIVILEGES ON SEQUENCE public.verification_ble_authorizations_id_seq TO service_role;
GRANT ALL PRIVILEGES ON SEQUENCE public.verification_ble_devices_id_seq TO service_role;

COMMENT ON TABLE public.verification_ble_qualifications IS
  'Migration 066: 90-second face-verified BLE qualification; closing or retrying the QR window never deducts units.';
COMMENT ON TABLE public.verification_ble_authorizations IS
  'Migration 066: short HMAC device authorization; final verification and deduction occur only after DEVICE_WORKING confirmation.';
COMMENT ON TABLE public.verification_ble_devices IS
  'Migration 066: service-only BLE device registry. Pairing codes are stored only as SHA-256 hashes.';

COMMIT;
